version: '3.1'

services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: criptomaniacos
    ports:
      - '5432:5432'
