name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: npm install

      - name: Prisma Generate
        run: npx prisma generate

      - name: Build
        run: npm run build
